[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions/"

[context.production]
  [context.production.environment]
    DEBUG = "False"
    SECRET_KEY = "your-secret-key-here"
    DATABASE_URL = "your-database-url-here"
