# Generated by Django 5.2.7 on 2025-10-05 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_cambio_actual', models.FloatField()),
                ('fecha_actualizacion_tasa', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alicuota', models.FloatField()),
                ('propietario', models.CharField(max_length=100)),
                ('inquilino', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado_bs', models.FloatField()),
                ('monto_pagado_usd', models.FloatField()),
                ('tasa_usd_fecha_pago', models.FloatField()),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('bs', 'Bs.F'), ('usd', 'USD')], max_length=20)),
                ('estado', models.CharField(default='pagado', max_length=20)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidad')),
            ],
        ),
    ]
