# Generated by Django 5.2.7 on 2025-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto_usd', models.FloatField()),
                ('monto_bs', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('aplicar_a_todas', models.BooleanField(default=False)),
                ('unidades', models.ManyToManyField(blank=True, to='core.unidad')),
            ],
        ),
    ]
