# Generated by Django 5.2.7 on 2025-10-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cuotaespecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotaespecial',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
