# Generated by Django 5.2.7 on 2025-10-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_usd', models.FloatField()),
                ('monto_total_bs_fecha_emision', models.FloatField()),
                ('tasa_usd_fecha_emision', models.FloatField()),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pagada', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidad')),
            ],
        ),
    ]
