# Generated by Django 5.2.7 on 2025-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conversion', models.DateField(auto_now_add=True)),
                ('monto_bs', models.FloatField()),
                ('monto_usd', models.FloatField()),
                ('tasa_usd', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
