# Generated by Django 5.2.7 on 2025-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversiondivisa',
            old_name='monto_bs',
            new_name='monto_destino',
        ),
        migrations.RenameField(
            model_name='conversiondivisa',
            old_name='monto_usd',
            new_name='monto_origen',
        ),
        migrations.AddField(
            model_name='conversiondivisa',
            name='tipo_operacion',
            field=models.CharField(choices=[('compra', 'Compra de USD (Bs → USD)'), ('venta', 'Venta de USD (USD → Bs)')], default='compra', max_length=10),
        ),
    ]
